# -*- coding: utf-8 -*-
"""Analyse quantitative du marché boursier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeCqpwUmuefDmwgMGgRtMlZ0bI4uJ09K

# Analyse quantitative du marché boursier à l'aide de Python

L'analyse quantitative en bourse implique l'utilisation de techniques mathématiques et statistiques pour comprendre, prédire et prendre des décisions d'investissement financier. Si vous souhaitez apprendre à réaliser une analyse quantitative des données boursières. Je vous expliquerai comment réaliser une analyse quantitative en bourse avec Python.


# Analyse quantitative du marché boursier : processus à suivre


L'analyse quantitative sur le marché boursier est une méthodologie financière qui utilise des techniques mathématiques et statistiques pour analyser les actions et les marchés financiers.

Vous trouverez ci-dessous le processus que nous pouvons suivre pour la tâche d’analyse quantitative du marché boursier :

- Définir clairement les objectifs et les questions auxquelles il faut répondre.
- Identifier les indicateurs clés de performance (KPI) pertinents pour l’analyse.
- Collectez des données historiques sur le marché boursier, y compris les prix, les volumes et d’autres indicateurs financiers pertinents.
- Nettoyez et prétraitez les données pour gérer les valeurs manquantes, les valeurs aberrantes et les erreurs.
- Effectuer une analyse initiale pour comprendre les distributions, les modèles et les corrélations des données.
- Mettre en œuvre diverses stratégies basées sur l’analyse quantitative.

Pour commencer cette tâche, nous avons besoin de données appropriées. J'ai trouvé un jeu de données idéal pour cette tâche. Vous pouvez le télécharger ici .
https://statso.io/2024/01/14/quantitative-analysis-case-study/

# Analyse quantitative du marché boursier à l'aide de Python
Maintenant, commençons la tâche d'analyse quantitative du marché boursier en important les bibliothèques Python nécessaires et l' ensemble de données :
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.templates.default = "plotly_white"

from google.colab import files
# Permettre à l'utilisateur de télécharger un fichier
uploaded = files.upload()

#Charger l'ensemble de  données
stocks_data = pd.read_csv('stocks.csv')

#Afficher les premiere ligne de l'ensemble de données
print(stocks_data.head())

"""L'ensemble de données contient les colonnes suivantes pour les données boursières :

- Ticker : Le symbole boursier.
- Date : La date de négociation.
- Ouvert : Le prix d'ouverture de l'action pour la journée.
- Haut : Le prix le plus élevé de l'action au cours de la journée.
- Bas : Le prix le plus bas de l'action au cours de la journée.
- Clôture : Le prix de clôture de l'action pour la journée.
- Clôture ajustée : Le prix de clôture ajusté, qui tient compte de toutes les actions de l'entreprise telles que les dividendes, les fractionnements d'actions, etc.
- Volume : Le nombre d'actions échangées au cours de la journée.

Pour réaliser une analyse quantitative, nous pouvons explorer divers concepts statistiques tels que les statistiques descriptives, l'analyse des séries chronologiques , l'analyse de corrélation, etc. Voici quelques analyses potentielles que nous pouvons réaliser :

1. Statistiques descriptives : Statistiques récapitulatives (moyenne, médiane, écart type, etc.) pour chaque action.
2. Analyse des séries chronologiques : tendances et modèles au fil du temps, en particulier pour les cours de clôture.
3. Analyse de la volatilité : dans quelle mesure le prix d’une action fluctue sur une période donnée.
4. Analyse de corrélation : Comment les cours des actions de différentes sociétés sont liés les uns aux autres.
5. Analyse comparative : Comparaison des performances de différentes actions.
6. Analyse du compromis risque-rendement : analyse de l’équilibre entre les risques et les récompenses potentiels de différentes actions, facilitant la gestion de portefeuille.

Mettons en œuvre tous ces concepts d’analyse quantitative du marché boursier un par un.

# Statistiques descriptives
Les statistiques descriptives fourniront des statistiques récapitulatives pour chaque action de l'ensemble de données. Nous examinerons des mesures telles que la moyenne, la médiane, l'écart type, etc., pour les cours de clôture :
"""

#Statistique descriptives pour chaque action
descriptive_stats = stocks_data.groupby('Ticker')['Close'].describe()
print(descriptive_stats)

"""Décomposons les résultats pour chaque action :

AAPL (Apple Inc.)

- Nombre : 62,0 (Nombre d'observations ou de jours de négociation inclus dans l'ensemble de données pour AAPL)

- Moyenne : 158,24 (le cours de clôture moyen)

- Écart type : 7,36 (mesure le degré de variation ou de dispersion des cours de clôture)

- Minimum : 145,31 (le prix de clôture le plus bas de l'ensemble de données)

- 25e percentile : 152,08 (25 % des cours de clôture sont inférieurs à cette valeur)

- Médiane (50%) : 158,06 (La valeur moyenne des cours de clôture)

- 75e percentile : 165,16 (75 % des cours de clôture sont inférieurs à cette valeur)

- Maximum : 173,57 (le prix de clôture le plus élevé de l'ensemble de données)

# GOOG (Alphabet Inc.)

Statistiques similaires à celles d'AAPL, mais pour GOOG. Le cours de clôture moyen est de 100,63, avec un écart type de 6,28, ce qui indique une variabilité moindre des cours de clôture par rapport à AAPL.

# MSFT (Microsoft Corporation)

L'ensemble de données comprend le même nombre d'observations pour MSFT. Son cours de clôture moyen est plus élevé (275,04) et son écart type (17,68), ce qui suggère une plus grande variabilité des prix que pour AAPL et GOOG.

# NFLX (Netflix Inc.)

NFLX affiche le prix de clôture moyen le plus élevé (327,61) parmi ces actions et l'écart type le plus élevé (18,55), indiquant la fluctuation de prix la plus importante.

# Analyse des séries chronologiques

Ensuite, nous procéderons à l'analyse des séries chronologiques pour examiner les tendances et les modèles au fil du temps, en nous concentrant sur les cours de clôture :
"""

#Analyse des series chronologiques
stocks_data['Date'] = pd.to_datetime(stocks_data['Date'])
pivot_data = stocks_data.pivot(index='Date', columns='Ticker', values='Close')

#Créer une intrigue secondaire
fig = make_subplots(rows=1, cols=1)

#Ajouter des traces pour chaque symbole boursier
for columns in pivot_data.columns:
  fig.add_trace(
      go.Scatter(x=pivot_data.index, y=pivot_data[columns], name=columns),
      row=1, col= 1

  )

#Mettre à jour la mise en page
fig.update_layout(
    title_text='Time Series of Closing Prices',
    xaxis_title='Date',
    yaxis_title='Closing Price',
    legend_title='Ticker',
    showlegend=True
 )

# Afficher l'intrigue
fig.show()

"""Le graphique ci-dessus présente la série chronologique des cours de clôture de chaque action (AAPL, GOOG, MSFT, NFLX) sur la période observée. Voici quelques observations clés :



1. Tendance : Chaque action affiche une tendance unique au fil du temps. Par exemple, AAPL et MSFT affichent une tendance générale à la hausse sur cette période.
2. Volatilité : Le cours des actions est très volatil. Par exemple, NFLX affiche des fluctuations plus prononcées que d'autres.
3. Performance comparative : Lors de la comparaison des actions, MSFT et NFLX se négocient généralement à des niveaux de prix plus élevés qu'AAPL et GOOG dans cet ensemble de données.

# Analyse de la volatilité

Concentrons-nous ensuite sur l'analyse de la volatilité. Nous calculerons et comparerons la volatilité (écart type) des cours de clôture de chaque action. Cela nous donnera un aperçu de l'ampleur des fluctuations des cours sur la période :
"""

#Analyse de la volatilité
volatility = pivot_data.std().sort_values(ascending=False)

fig = px.bar(volatility,
             x=volatility.index,
             y=volatility.values,
             labels={'x': 'Ticker', 'y': 'Standard Deviation'},
             title='Volatility of Closing Prices (Standard Deviation)'
             )

#Montrer la figure
fig.show()

"""Le graphique à barres et les données qui l'accompagnent montrent la volatilité (mesurée en écart type) des cours de clôture de chaque action. Voici leur classement en termes de volatilité :

1. NFLX : Volatilité la plus élevée avec un écart type d'environ 18,55.
2. MSFT : Le prochain plus élevé, avec un écart type d'environ 17,68.
3. AAPL : Volatilité inférieure par rapport à NFLX et MSFT, avec un écart type d'environ 7,36.
4. GOOG : Le moins volatil de cet ensemble, avec un écart type d'environ 6,28.

Cela indique que les actions NFLX et MSFT étaient plus sujettes aux fluctuations de prix au cours de cette période par rapport à AAPL et GOOG.

# Analyse de corrélation

Ensuite, nous effectuerons une analyse de corrélation pour comprendre comment les cours des actions de ces sociétés sont liés les uns aux autres :
"""

# Analyse de corrélation
correlation_matrix = pivot_data.corr()

fig = go.Figure(data=go.Heatmap(
    z=correlation_matrix.values,
    x=correlation_matrix.columns,
    y=correlation_matrix.columns,
    colorscale='blues',
    colorbar=dict(title='Correlation')
))

#Mettre à jour la mise en page

fig.update_layout(
    title='Correlation Matrix of Closing Prices',
    xaxis_title='Ticker',
    yaxis_title='Ticker',
    width=800,
    height=800
)

# Montrer la figure
fig.show()

"""La carte thermique ci-dessus présente la matrice de corrélation des cours de clôture des quatre actions (AAPL, GOOG, MSFT, NFLX). Voici ce que suggèrent les coefficients de corrélation :

- Les valeurs proches de +1 indiquent une forte corrélation positive, ce qui signifie que lorsque le prix d'une action augmente, celui de l'autre a tendance à augmenter également.

- Les valeurs proches de -1 indiquent une forte corrélation négative, où l'augmentation du prix d'une action correspond à une diminution de l'autre.

- Les valeurs autour de 0 indiquent un manque de corrélation.

La carte thermique montre différents degrés de corrélation positive entre les cours des actions, certaines paires affichant des corrélations plus fortes que d'autres. Par exemple, AAPL et MSFT semblent présenter une corrélation positive relativement plus élevée.


# Analyse comparative

Passons maintenant à l'analyse comparative. Dans cette étape, nous comparerons la performance de différentes actions en fonction de leurs rendements sur la période. Nous calculerons la variation en pourcentage des cours de clôture de chaque action entre le début et la fin de la période :
"""

# Calcul du pourcentage de variation des cours de cloture
percentage_change = ((pivot_data.iloc[-1] - pivot_data.iloc[0])/pivot_data.iloc[0])*100

fig = px.bar(percentage_change,
             x=percentage_change.index,
             y=percentage_change.values,
             labels={'x': 'Ticker', 'y': 'Percentage Change'},
             title='Percentage Change of Closing Prices'

#Afficher l'intrigue             )
fig.show()

"""Le graphique à barres et les données qui l'accompagnent montrent la variation en pourcentage des cours de clôture des actions du début à la fin de la période observée :

- MSFT : Le changement positif le plus élevé d'environ 16,10 %.

- AAPL a enregistré une variation positive d'environ 12,23 %. Cela indique une performance solide, quoique légèrement inférieure à celle de MSFT.

- GOOG : a affiché une légère variation négative d'environ -1,69 %. Cela indique une légère baisse du cours de son action sur la période observée.

- NFLX : L'action a connu la variation négative la plus significative, soit environ -11,07 %. Cela suggère une baisse notable du cours de son action au cours de la période.

# Analyse quotidienne du risque par rapport au rendement

Pour réaliser une analyse risque/rendement, nous calculerons le rendement quotidien moyen et l'écart type de chaque action. L'écart type servira d'indicateur du risque, tandis que le rendement quotidien moyen représente le rendement attendu.

Nous tracerons ensuite ces valeurs pour évaluer visuellement le profil risque-rendement de chaque action. Les actions présentant un rendement moyen plus élevé et un risque plus faible (écart type) sont généralement plus attractives, mais les décisions d'investissement dépendent souvent de la tolérance au risque de l'investisseur :
"""

daily_returns = pivot_data.pct_change().dropna()

#Recalcul du rendement quotidien moyen et de l'ecart type (risque)
avg_daily_returns = daily_returns.mean()
risk = daily_returns.std()

#Création d'un dataFrame pour le traçage
risk_return_df = pd.DataFrame({'Average Daily Returns': avg_daily_returns, 'Risk': risk})

fig = go.Figure()


#Ajouter des points de nuage de points
fig.add_trace(go.Scatter(
    x=risk_return_df['Risk'],
    y=risk_return_df['Average Daily Returns'],
    mode='markers+text',
    text=risk_return_df.index,
    textposition='top center',
    marker=dict(
        size=10)))


#Mettre à jour la mise en page
fig.update_layout(
    title='Risk vs. Return Analysis',
    xaxis_title='Risk (Standard Deviation)',
    yaxis_title='Average Daily Returns',
    showlegend=False
)
fig.show()

"""Ainsi, AAPL présente le risque le plus faible, associé à un rendement quotidien moyen positif, ce qui suggère un investissement plus stable et des rendements réguliers.

GOOG présente une volatilité plus élevée qu'AAPL et, en moyenne, un rendement quotidien légèrement négatif, ce qui indique un investissement plus risqué et moins rentable durant cette période.

MSFT présente un risque modéré avec le rendement quotidien moyen le plus élevé, ce qui suggère un investissement potentiellement plus rentable, bien qu'avec une volatilité plus élevée par rapport à AAPL.

NFLX présente le risque le plus élevé et un rendement quotidien moyen négatif, indiquant qu'il s'agit de l'investissement le plus volatil et le moins rentable parmi ces actions sur la période analysée.

# Résumé
Voici comment réaliser une analyse quantitative du marché boursier avec Python. L'analyse quantitative du marché boursier est une méthodologie financière qui utilise des techniques mathématiques et statistiques pour analyser les actions et les marchés financiers.
"""